version: '3.8'

services:
  # Production build
  aura-villas-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aura-villas-production
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - aura-network
    restart: unless-stopped
    profiles:
      - production

  # Development with hot reload
  aura-villas-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: aura-villas-development
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - WATCHPACK_POLLING=true  # Enable hot reload in Docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - aura-network
    restart: unless-stopped
    profiles:
      - development

  # Nginx reverse proxy (optional - for production-like setup)
  nginx:
    image: nginx:alpine
    container_name: aura-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - aura-villas-prod
    networks:
      - aura-network
    restart: unless-stopped
    profiles:
      - production
      - with-nginx

networks:
  aura-network:
    driver: bridge
    name: aura-villas-network

# Volumes for persistent data (if needed)
volumes:
  aura-data:
    driver: local