spec:
  name: aura-villas-bali
  region: sgp
  domains:
    - domain: auravillasbali.com
      type: PRIMARY
      zone: auravillasbali.com
  
  services:
    - name: web
      environment_slug: node-js
      github:
        repo: aura-villas-bali
        branch: main
        deploy_on_push: true
      build_command: npm run build
      run_command: npm start
      http_port: 3000
      instance_count: 1
      instance_size_slug: professional-xs
      routes:
        - path: /
      envs:
        - key: NODE_ENV
          value: production
        - key: NEXT_PUBLIC_SITE_URL
          value: https://auravillasbali.com
        - key: PORT
          value: "3000"
      health_check:
        http_path: /
        initial_delay_seconds: 10
        period_seconds: 10
        timeout_seconds: 5
        success_threshold: 1
        failure_threshold: 3